---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
  - package-ecosystem: docker
    directory: "/ha_mcp_server"
    schedule:
      interval: monthly
    commit-message:
      prefix: "build"
